### ISSUE TITLE
Problema de performance

### ISSUE THREAD

**Issue by thmoisesexpenseon** [ExpenseOn/expenseon.repository.mysql#2]
Noite pessoal,

É possível remover essa linha?

https://github.com/ExpenseOn/expenseon.repository.mysql/blob/f02538a23d16e66af82ac97f00fa298e4849ec1f/ExpenseOn.Repository.MySql/Repository.cs#L28

Essa chamada está gerando uma carga gigante de processamento e uso de memória quando relacionado à IoC do AutoFac.

Em Uma atividade interna precisei referenciar no construtor do RegrasSumary um serviço que tinha por dependência um Repositório herdado dessa classe citada. Devido à essa linha a aplicação "sentou". Aparentemente o Dommel usa Reflection nesse ponto, e acaba gerando uma sobrecarga desnecessário no construtor.

Minha sugestão, já que atribui à uma variável privada, que só é usada em uma função em especifico, seria levar esse carregamento pra dentro da função em que é necessário e limpar esse construtor.

**Comment by alexmurari** [comment]
Só pra ficar registrado:

O problema está na aplicação que está utilizando essa biblioteca, não na biblioteca em si.

Uma mesma requisição/operação está instanciando as classes de repositório dezenas de vezes, o trecho `_pkPropertyMap = ...` está no construtor da classe, o que está certo. A correção definitiva seria a aplicação que usa essa biblioteca tratar essas classes como `scoped` e não como `transient` e instancia-las apenas uma vez por requisição (escopo).

Por hora, em conversa com @thmoisesexpenseon, vamos transformar esse campo em `lazy` e popular o valor apenas quando necessário ao invés de fazer isso no construtor.

**Comment by alexmurari** [comment]
Fechado através da PR #3 .
